### ISSUE TITLE
Add flexibility around which WildFly Swarm fractions are installed

### ISSUE THREAD

**Issue by kenfinnigan** [forge/wildfly-swarm-addon#1]
Currently the JAX-RS fraction is installed by default.

In an ideal world, we'd probably want to tailor it so that which fraction(s) is installed is dependent on which project facets are installed. For instance, if JAX-RS is installed then install appropriate fraction, if CDI do this, if JPA do this, if CDI and JAX-RS do this.

Downside is that there is logic required to know which fractions to use in which situations, so not sure if that's ok being encoded into a Forge plugin or should be external somehow

**Comment by gastaldi** [comment]
Yes, we need to better think abiut it.

What if we had Drools rules to do the condition for us? Forge could also fire events when a facet is installed in a Project to notify observers about a technology being set up.

Thoughts?

----- Mensagem original -----
De: Ken Finnigan <notifications@github.com>
Para: forge/wildfly-swarm-addon <wildfly-swarm-addon@noreply.github.com>
Enviadas: Wed, 13 May 2015 14:56:07 -0400 (EDT)
Assunto: [wildfly-swarm-addon] Add flexibility around which WildFly Swarm fractions are installed (#1)

Currently the JAX-RS fraction is installed by default.

In an ideal world, we'd probably want to tailor it so that which fraction(s) is installed is dependent on which project facets are installed. For instance, if JAX-RS is installed then install appropriate fraction, if CDI do this, if JPA do this, if CDI and JAX-RS do this.

Downside is that there is logic required to know which fractions to use in which situations, so not sure if that's ok being encoded into a Forge plugin or should be external somehow

---
Reply to this email directly or view it on GitHub:
https://github.com/forge/wildfly-swarm-addon/issues/1

**Comment by agoncal** [comment]
I like the idea of events (CDI). Each time a facet is installed, an event is fired. The Swarm addon just needs to listen to this even and add the needed fraction.

**Comment by gastaldi** [comment]
From the #wildfly-swarm IRC  channel:

> bobmcw: hey, would it be weird for the forge add-on to take a list of fractions (undertow, messaging, transactions, etc) and generate appropriate <dependency> in the resulting pom.xml?
> gastaldi: of course not 
> gastaldi: that would be awesome
> bobmcw: I've never used forge, tbh, so I have no idea what's appropriate
> bobmcw: basically X -> org.wildfly.swarm:wildfly-swarm-X:${version}
